#!/usr/bin/env python3
"""Build README.md (the GitHub profile page) from RESUME.md.

The profile page shows the full resume, so README.md is generated, never hand-edited.
CI runs this on every push that touches RESUME.md; run it locally with:

    python3 scripts/build_readme.py

It copies RESUME.md with the HTML comments (maintenance notes) removed and adds a link to
the CI-built PDF on the contact line.
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "RESUME.md"
TARGET = ROOT / "README.md"
PDF_LINK = "[Resume PDF](assets/Caleb-Easton-Resume.pdf)"

HEADER = (
    "<!--\n"
    "  GENERATED from RESUME.md by scripts/build_readme.py, which CI runs on every push that\n"
    "  touches RESUME.md. Do not edit this file by hand: edit RESUME.md and push.\n"
    "-->\n\n"
)


def build(text: str) -> str:
    text = re.sub(r"<!--.*?-->", "", text, flags=re.S)  # maintenance notes stay in RESUME.md
    text = re.sub(r"[ \t]+\n", "\n", text)
    text = re.sub(r"\n{3,}", "\n\n", text).strip()
    text = re.sub(r"(\n---)+$", "", text).strip()  # no trailing horizontal rule

    lines = text.split("\n")
    contact = next(i for i, line in enumerate(lines) if "mailto:" in line)
    if PDF_LINK not in lines[contact]:
        lines[contact] += f" · {PDF_LINK}"

    return HEADER + "\n".join(lines) + "\n"


if __name__ == "__main__":
    TARGET.write_text(build(SOURCE.read_text(encoding="utf-8")), encoding="utf-8")
    print(f"Wrote {TARGET.relative_to(ROOT)} from {SOURCE.relative_to(ROOT)}")
